### ISSUE TITLE
Possibly a trellis-cli issue but discovered with deploy action

### ISSUE THREAD

**Issue by conradfuhrman** [roots/trellis-deploy-action#1]
### Terms

- [X] I have read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
- [X] This request is not a duplicate of an existing issue
- [X] I have read the [docs](https://roots.io/docs/) and followed them (if applicable)
- [X] I have seached the [Roots Discourse](https://discourse.roots.io/) for answers and followed them (if applicable)
- [X] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

#### What's wrong?
When setting up a new trellis project using the cli and using `trellis key generate` the keys and secrets are created on the repository, however deploy doesn't work.

#### What have you tried?
When running the `ssh-keyscan -t ed25519 -H github.com ` with the proper item in the correct hosts file, and editing the private key, it seems to then work.

#### What insights have you gained?
Possibly something is improper with the cli for generating a key related this action

#### Possible solutions
Double check what is actually being generated from the CLI for this action, or revise the instructions.

#### Temporary workarounds
See above.

### Steps To Reproduce

Create a new Trellis project via the CLI
Edit all applicable files suck as wordpress_sites, vault, and hosts for a staging environmet
Run trellis key generate to connect everything up
Try to deploy using the action

### Expected Behavior

A deployable site with the action.

### Actual Behavior

Keypair failure until I generate a new key using the `ssh-keyscan -t ed25519 -H github.com` directly.

### Versions

1.12 trellis, main on this repo.

**Comment by tjedrak** [comment]
Happens to me as well.

I'm now on circle-cli 1.5.0.
Tried to re-generate and got this:

```                                         
[✓] Generated SSH key [/Users/xxxx/.ssh/trellis_xxxx_test_ed25519]
[✓] Moved public key [/Users/xxxx/WebApps/xxxx/trellis/public_keys/trellis_xxxx_test_ed25519.pub]
[✓] GitHub private key secret set [TRELLIS_DEPLOY_SSH_PRIVATE_KEY]
[✓] GitHub deploy key added [Trellis deploy]
Error: could not set SSH known hosts. ssh-keyscan command failed.
```
That is why I added TRELLIS_DEPLOY_SSH_KNOWN_HOSTS manually.

Meanwhile when I deploy with GH Action I got this:

```
Run webfactory/ssh-agent@v0.5.4
Adding GitHub.com keys to /home/runner/.ssh/known_hosts
Starting ssh-agent
SSH_AUTH_SOCK=/tmp/ssh-PLsoLXgXT510/agent.1785
SSH_AGENT_PID=1786
Adding private key(s) to agent
Identity added: (stdin) (Trellis deploy)
Key(s) added:
256 SHA256:cQbCmhlRe+sZQ7KhXT5KyXkXHKc7BMl+aahK5GASdG4 Trellis deploy (ED25519)
Configuring deployment key(s)
Comment for (public) key 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJwjx7rrhwl4dmvRBbPuJHzuXMPNlVPf+EVfSnluQwOu Trellis deploy' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
Comment for (public) key '' does not match GitHub URL pattern. Not treating it as a GitHub deploy key.
```

and I think that kills the whole process:

```
TASK [Gathering Facts] *********************************************************
[WARNING]: Unhandled error in Python interpreter discovery for host
x.x.x.x: Failed to connect to the host via ssh: Host key verification
failed.
System info:
  Ansible 2.10.16; Linux
  Trellis version (per changelog): "Update default ssh key paths"
---------------------------------------------------
Data could not be sent to remote host "x.x.x.x". Make sure this host
can be reached over ssh: Host key verification failed.
fatal: [x.x.x.x]: UNREACHABLE! => {"changed": false, "unreachable": true}

PLAY RECAP *********************************************************************
x.x.x.x              : ok=2    changed=0    unreachable=1    failed=0    skipped=5    rescued=0    ignored=0   
localhost                  : ok=0    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   

exit status 4
Error: Process completed with exit code 1.
```

**Comment by swalkinshaw** [comment]
Next trellis-cli version will have improved failure output for keyscan: https://github.com/roots/trellis-cli/pull/253

However, the known hosts value should **not** be for `github.com`; it needs to be for _your_ remote Trellis server.

GitHub is the client SSH'ing into your server, so this action uses `shimataro/ssh-key-action` which configures the SSH client on the GitHub action runner environment. That's why it needs your remote host to be known.

trellis-cli under the hood basically takes `ansible all --list-hosts` to scan all your hosts. The manual way is:

```bash
ssh-keyscan -t ed25519 -H example.com
```

**Comment by conradfuhrman** [comment]
Thanks @swalkinshaw, will test the new cli version for the next provision. For the issue we were using the IP and/or the domain of our site which matched what was in our hosts file for the applicable environment. Might be awesome to link the generate for that part to read what is in the hosts file :)

**Comment by swalkinshaw** [comment]
https://github.com/roots/trellis-cli/releases/tag/v1.5.1 should hopefully handle this better. Please let me know how it goes... and if there's a bug, report it on https://github.com/roots/trellis-cli please 😄 

Closing this issue since it's not specifically for this repo

**Comment by tjedrak** [comment]
> However, the known hosts value should **not** be for `github.com`; it needs to be for _your_ remote Trellis server.
> 
> GitHub is the client SSH'ing into your server, so this action uses `shimataro/ssh-key-action` which configures the SSH client on the GitHub action runner environment. That's why it needs your remote host to be known.

Sorry for the late reply, yes that did the trick. I just went with the README file and I got suggested that I need to add `github.com`.

All works now! Brilliant, thanks :)
